// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzb6B33gdO4TDs_BCQg88qv6pwrtw3MmY',
    appId: '1:700238368033:web:d2f4bc388b832322f5c260',
    messagingSenderId: '700238368033',
    projectId: 'flutter-gpt-1a88c',
    authDomain: 'flutter-gpt-1a88c.firebaseapp.com',
    storageBucket: 'flutter-gpt-1a88c.appspot.com',
    measurementId: 'G-1R4MHYZQX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EjTaNvOC32t35aWvtYr6pUldv78b0CY',
    appId: '1:700238368033:android:839f16f306b7c1aef5c260',
    messagingSenderId: '700238368033',
    projectId: 'flutter-gpt-1a88c',
    storageBucket: 'flutter-gpt-1a88c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApmGPMErGY9W6LKSUeFwHt7-NCDo-QRMg',
    appId: '1:700238368033:ios:0e69eea1c5086f32f5c260',
    messagingSenderId: '700238368033',
    projectId: 'flutter-gpt-1a88c',
    storageBucket: 'flutter-gpt-1a88c.appspot.com',
    iosClientId: '700238368033-07u5h6ik43q4vvbv8v84lt78ggbnmq4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApmGPMErGY9W6LKSUeFwHt7-NCDo-QRMg',
    appId: '1:700238368033:ios:0e69eea1c5086f32f5c260',
    messagingSenderId: '700238368033',
    projectId: 'flutter-gpt-1a88c',
    storageBucket: 'flutter-gpt-1a88c.appspot.com',
    iosClientId: '700238368033-07u5h6ik43q4vvbv8v84lt78ggbnmq4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptFlutter',
  );
}
